[workspace]
members = [
    "crates/salah-core",
    "crates/salah-cli",
    "crates/salah-time",
    "crates/salah-location",
    "crates/salah-engine",
    "crates/salah-update",
    "crates/salah-update-store",
    "crates/salah-wasm",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
