#!/bin/sh
# Regenerate and verify F2-TZ0 fixtures from pinned IANA archives.
# Network access is for fixture generation only; salah-time never uses it.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
WORK=$(mktemp -d "${TMPDIR:-/tmp}/salah-tzbuild.XXXXXX")
trap 'rm -rf "$WORK"' 0

curl -fsSL -o "$WORK/tzdata2026d.tar.gz" \
  https://data.iana.org/time-zones/releases/tzdata2026d.tar.gz
curl -fsSL -o "$WORK/tzcode2026d.tar.gz" \
  https://data.iana.org/time-zones/releases/tzcode2026d.tar.gz

# Verify downloads before extracting or executing source code.
python3 - "$HERE/manifest.json" "$WORK" <<'PY'
import hashlib
import json
import pathlib
import sys

manifest = json.loads(pathlib.Path(sys.argv[1]).read_text())
work = pathlib.Path(sys.argv[2])
for archive, expected in [
    ("tzdata2026d.tar.gz", manifest["source_archive"]["sha256"]),
    ("tzcode2026d.tar.gz", manifest["generator"]["tzcode_archive_sha256"]),
]:
    actual = hashlib.sha256((work / archive).read_bytes()).hexdigest()
    if actual != expected:
        raise SystemExit(f"{archive}: SHA-256 mismatch: {actual}")
print("Pinned IANA archive hashes verified")
PY

mkdir "$WORK/build" "$WORK/out"
tar -xzf "$WORK/tzdata2026d.tar.gz" -C "$WORK/build"
tar -xzf "$WORK/tzcode2026d.tar.gz" -C "$WORK/build"
make -C "$WORK/build" zic
VERSION=$("$WORK/build/zic" --version)
if [ "$VERSION" != 'zic (tzcode) 2026d' ]; then
  echo "Unexpected zic version: $VERSION" >&2
  exit 1
fi
(cd "$WORK/build" && ./zic -b slim -d "$WORK/out" \
  africa antarctica asia australasia etcetera europe \
  northamerica southamerica factory backward)

# Validate generated bytes before touching the checked-in fixture pack.
python3 - "$HERE/manifest.json" "$WORK/out" "$WORK/build/LICENSE" <<'PY'
import hashlib
import json
import pathlib
import sys

manifest = json.loads(pathlib.Path(sys.argv[1]).read_text())
out = pathlib.Path(sys.argv[2])
license_path = pathlib.Path(sys.argv[3])
for zone in manifest["zones"]:
    data = (out / zone["id"]).read_bytes()
    actual = hashlib.sha256(data).hexdigest()
    if len(data) != zone["bytes"] or actual != zone["sha256"]:
        raise SystemExit(f"{zone['id']}: fixture mismatch: {len(data)} bytes, SHA-256 {actual}")
license_hash = hashlib.sha256(license_path.read_bytes()).hexdigest()
if license_hash != manifest["license"]["sha256"]:
    raise SystemExit(f"LICENSE: SHA-256 mismatch: {license_hash}")
print("Generated TZif and LICENSE hashes verified")
PY

mkdir -p "$HERE/tzif"
for zone in Etc/UTC America/Chicago Europe/London Asia/Kathmandu \
  Pacific/Kiritimati Pacific/Apia; do
  cp "$WORK/out/$zone" "$HERE/tzif/$(echo "$zone" | tr '/' '_').tzif"
done
cp "$WORK/build/LICENSE" "$HERE/LICENSE"
echo "F2-TZ0 fixture pack matches fixtures/manifest.json"
